import { createSlice } from "@reduxjs/toolkit";

// Create a slice of the Redux store for user authentication
export const userSlice = createSlice({
  name: 'user', // The name of the slice
  initialState: {
    isAuthenticated: false, // Initial state for authentication
  },
  reducers: {
    login: (state) => {
      state.isAuthenticated = true; // Set isAuthenticated to true on login
    },
    logout: (state) => {
      state.isAuthenticated = false; // Set isAuthenticated to false on logout
    },
  },
});

// Export the actions generated by createSlice
export const { login, logout } = userSlice.actions;

// Export the reducer to be included in the store
export default userSlice.reducer;